Game.create!([
  {title: "League of Legends", summary: "League of Legends is a fast-paced, competitive online game that blends the speed and intensity of an RTS with RPG elements. Two teams of powerful champions, each with a unique design and playstyle, battle head-to-head across multiple battlefields and game modes. With an ever-expanding roster of champions, frequent updates and a thriving tournament scene, League of Legends offers endless replayability for players of every skill level.", image_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/lxoumgqbbj3erxgq6a6l.jpg", video_url: "https://youtu.be/8fwwGCr1-po"},
  {title: "Yakuza 0", summary: "Yakuza 0 is a prequel set in 1988 to the Yakuza series of games developed by Sega, taking place before the first Yakuza game. Like in the previous games, the game's main setting is the fictional town of Kamurocho in Tokyo. The story follows Kazuma Kiryu as a junior yakuza member who finds himself in a world of trouble when a simple debt collection goes wrong and his mark winds up murdered. Kiryu and Majima can each switch between three brutal hand-to-hand combat styles on the fly to create the most fluid beatdowns ever experienced in a Yakuza game.", image_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rki.jpg", video_url: "https://youtu.be/QTM1PP5d6ss"},
  {title: "Persona 5", summary: "Persona 5, a turn-based JRPG with visual novel elements, follows a high school student with a criminal record for a crime he didn't commit. Soon he meets several characters who share similar fates to him, and discovers a metaphysical realm which allows him and his friends to channel their pent-up frustrations into becoming a group of vigilantes reveling in aesthetics and rebellion while fighting corruption.", image_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r76.jpg", video_url: "https://youtu.be/VcQGMdqMoAc"},
  {title: "Bloodborne", summary: "Introducing Bloodborne, the latest Action RPG from renowned Japanese developer FromSoftware, makers of the hit Dark Souls series. Face your fears as you search for answers in the ancient city of Yharnam, now cursed with a strange endemic illness spreading through the streets like wildfire. Danger, death and madness lurk around every corner of this dark and horrific world, and you must discover its darkest secrets in order to survive.", image_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rba.jpg", video_url: "https://youtu.be/rMxEpPCSH5A"},
  {title: "Resident Evil 2", summary: "In Resident Evil 2, the classic action, tense exploration, and puzzle solving gameplay that defined the Resident Evil series returns. Players join rookie police officer Leon Kennedy and college student Claire Redfield, who are thrust together by a disastrous outbreak in Raccoon City that transformed its population into deadly zombies. Both Leon and Claire have their own separate playable campaigns, allowing players to see the story from both characters’ perspectives. The fate of these two fan favorite characters is in players hands as they work together to survive and get to the bottom of what is behind the terrifying attack on the city. Will they make it out alive?", image_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1ir3.jpg", video_url: "https://youtu.be/CWl0hOeJvzA"},
  {title: "Hollow Knight", summary: "Hollow Knight is a challenging, beautiful action adventure game set in the vast, inter-connected underground kingdom of Hallownest. A 2D action game with an emphasis on skill and exploration, Hollow Knight has you fighting a fearsome host of deadly creatures, avoiding intricate traps and solving ancient mysteries as you make your own way through fungal wastes, forests of bone, and ruined underground cities.", image_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rgi.jpg", video_url: "https://youtu.be/-qVVO69Cgcs"},
  {title: "River City Girls", summary: "River City Girls stars Kyoko and Misako, two street-tough high-schoolers who must fight their way through the six regions of River City to rescue their kidnapped boyfriends, series mainstays Kunio and Riki. Along the way, they’ll utilize an arsenal of combos, counters, throws, and special attacks; battle an assortment of enemies; accept numerous side quests; level up with experience points; interact with NPCs (including guest stars from past River City games); and shop for a variety of items, food, and gear to boost stats and unlock new abilities. The girls can even wield weapons and recruit defeated foes to join them in combat!", image_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1mgx.jpg", video_url: "https://youtu.be/40MRASC-Ndw"},
  {title: "The Outer Worlds", summary: "In The Outer Worlds, you awake from hibernation on a colonist ship that was lost in transit to Halcyon, the furthest colony from Earth located at the edge of the galaxy, only to find yourself in the midst of a deep conspiracy threatening to destroy it. As you explore the furthest reaches of space and encounter various factions, all vying for power, the character you decide to become will determine how this player-driven story unfolds. In the corporate equation for the colony, you are the unplanned variable.", image_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1s7h.jpg", video_url: "https://youtu.be/XmyF8IjfSUI"},
  {title: "Pokemon Sword/Shield", summary: "The eighth generation of Pokemon comes to Nintendo Switch! Become a Pokémon Trainer and embark on a new journey in the new Galar region. Choose from one of three new partner Pokémon: Grookey, Scorbunny, or Sobble to embark on an all new adventure. You'll encounter new and familiar Pokémon as you catch, battle, and trade Pokémon while exploring new areas and uncovering an all-new story.", image_url: "https://assets.vg247.com/current//2019/10/pokemon-sword-shield.jpg", video_url: "https://youtu.be/p_dgvgpC8Nw"},
  {title: "Devil May Cry 5", summary: "A brand new entry in the legendary over-the-top action series comes, complete with its signature blend of high-octane stylized action and otherworldly and original characters the series is known for. Director Hideaki Itsuno and the core team have reunited to create the most over the top, technically advanced, utterly insane action experience of this generation. Years have passed since the legions of hell have set foot in this world, but now a new demonic invasion has begun, and humanity’s last hope will rest in the hands of three lone demon hunters, each offering a radically different play style. United by fate and a thirst for vengeance, these demon hunters will have to face their demons if they hope to survive.", image_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rb4.jpg", video_url: "https://youtu.be/MWxlbnI9mpU"},
  {title: "Shovel Knight", summary: "Shovel Knight is a sweeping classic action adventure game with awesome gameplay, memorable characters, and an 8-bit retro aesthetic. It's a hot mashup of new and old! You play as the eponymous Shovel Knight, a small knight with a huge quest. Shovel Knight has come to this land with two goals: to defeat the evil Enchantress and quest for his lost beloved. He wields a Shovel Blade: a multipurpose weapon whose techniques have now been lost to the ages. Always honest and helpful, Shovel Knight is a shining example of the code of Shovelry: Slash Mercilessly and Dig Tirelessly!", image_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1p9i.jpg", video_url: "https://youtu.be/unn0rgsa5UU"},
  {title: "The Legend of Zelda: Breath of the Wild", summary: "Step into a world of discovery, exploration and adventure in The Legend of Zelda: Breath of the Wild, a boundary-breaking new game in the acclaimed series. Travel across fields, through forests and to mountain peaks as you discover what has become of the ruined kingdom of Hyrule in this stunning open-air adventure.", image_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1p98.jpg", video_url: "https://youtu.be/zw47_q9wbBE"},
  {title: "Windjammers", summary: "Windjammers (also known as Flying Power Disc in Japan) is a fast paced sports arcade game originally released by Data East on the Neo Geo arcade system in 1994, but has been remastered for modern systems. The game mechanics are essentially the same as Pong or air hockey, where players continuously shoot the disc at the goal zone of the opponent attempting to score. The game can be played against the computer or in a 2 player versus.", image_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/f8z0picpbymabhzsrpsz.jpg", video_url: "https://youtu.be/-tYWIOI0SQI"},
  {title: "Death Stranding", summary: "From legendary game creator Hideo Kojima comes an all-new, genre-defying experience for the PlayStation 4. You play as Sam Bridges (voiced and modled by actor Norman Reedus) and must brave a world utterly transformed by the Death Stranding. Carrying the disconnected remnants of our future in his hands, he embarks on a journey to reconnect the shattered world one step at a time.", image_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1n3s.jpg", video_url: "https://youtu.be/tCI396HyhbQ"},
  {title: "Luigi's Mansion 3", summary: "Luigi embarks on a dream vacation with Mario and friends upon receiving an invitation to a luxurious hotel. However, his dream quickly becomes a nightmare when King Boo reveals everything had been a ploy to capture Mario and friends. With the assistance of Professor E. Gadd once again, the reluctant and cowardly hero Luigi traverses up and down treacherous floors of the now-ominous hotel on a quest to save them.", image_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rcc.jpg", video_url: "https://youtu.be/GHhY-SUYOms"},
  {title: "Doom (2016)", summary: "Developed by id software, the studio that pioneered the first-person shooter genre and created multiplayer Deathmatch, DOOM returns as a brutally fun and challenging modern-day shooter experience. Relentless demons, impossibly destructive guns, and fast, fluid movement provide the foundation for intense, first-person combat – whether you’re obliterating demon hordes through the depths of Hell in the single-player campaign, or competing against your friends in numerous multiplayer modes. Expand your gameplay experience using DOOM SnapMap game editor to easily create, play, and share your content with the world.", image_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1nc7.jpg", video_url: "https://youtu.be/QvYR4GVXS7E"},
  {title: "Inside", summary: "An atmospheric 2D side-scroller in which, hunted and alone, a boy finds himself drawn into the center of a dark project and struggles to preserve his identity.", image_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r7z.jpg", video_url: "https://youtu.be/op4G1--kb-g"},
  {title: "The Witness", summary: "You wake up, alone, on a strange island full of puzzles that will challenge and surprise you. You don't remember who you are, and you don't remember how you got here, but there's one thing you can do: explore the island in hope of discovering clues, regaining your memory, and somehow finding your way home. The Witness is a single-player game in an open world with dozens of locations to explore and over 500 puzzles. This game respects you as an intelligent player and it treats your time as precious. There's no filler; each of those puzzles brings its own new idea into the mix. So, this is a game full of ideas.", image_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1nc1.jpg", video_url: "https://youtu.be/i7h7AleSCF4"},
  {title: "Journey", summary: "In Journey the player controls a robed figure in a vast desert, traveling towards a mountain in the distance. Other players on the same journey can be discovered, and two players can meet and assist each other, but they cannot communicate via speech or text and cannot see each other's names. The only form of communication between the two is a musical chime. This chime also transforms dull, stiff pieces of cloth found throughout the levels into vibrant red, affecting the game world and allowing the player to progress through the levels. The robed figure wears a trailing scarf, which when charged by approaching floating pieces of cloth, briefly allows the player to float through the air.", image_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1q8q.jpg", video_url: "https://youtu.be/61DZC-60x20"},
  {title: "Spider-Man", summary: "Starring the world’s most iconic Super Hero, Spider-Man features the acrobatic abilities, improvisation and web-slinging that the wall-crawler is famous for, while also introducing elements never-before-seen in a Spider-Man game. From traversing with parkour and utilizing the environment, to new combat and blockbuster set pieces, it’s Spider-Man unlike any you’ve played before.", image_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r77.jpg", video_url: "https://youtu.be/q4GdJVvdxss"},
  {title: "God of War (2018)", summary: "From Santa Monica Studio and creative director Cory Barlog comes a new beginning for one of gaming’s most recognizable icons. Living as a man outside the shadow of the gods, Kratos must adapt to unfamiliar lands, unexpected threats, and a second chance at being a father. Together with his son Atreus, the pair will venture into the brutal Norse wilds and fight to fulfill a deeply personal quest.", image_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r6u.jpg", video_url: "https://youtu.be/rxrbXP546OU"},
  {title: "NieR Automata", summary: "The game is set in the same universe as NieR, a spin-off of the Drakengard series, and takes place several thousand years after the events of that game. Humanity has fled to the moon to escape an invading machine army from another world. Combat androids called YoRHa remain on the planet to fight in a proxy war against the invaders.", image_url: "https://images.igdb.com/igdb/image/upload/t_cover_big/qhok1pi6egmfizjjii7r.jpg", video_url: "https://youtu.be/K6Y4wC063NE"}
])

Tag.create!([
  {name: "Casual"},
  {name: "Experienced"},
  {name: "Short (0-10 Hours)"},
  {name: "Medium (10-30 Hours)"},
  {name: "Long (30+ Hours)"},
  {name: "Replayable"},
  {name: "One and Done"},
  {name: "Multiplayer/Cooperative"},
  {name: "Singleplayer"},
  {name: "PC"},
  {name: "PS4"},
  {name: "Xbox One"},
  {name: "Nintendo Switch"},
  {name: "Fantasy"},
  {name: "Sci-Fi"},
  {name: "Action/Adventure"},
  {name: "Horror"},
  {name: "Survival"},
  {name: "Party"},
  {name: "Warfare"},
  {name: "Shooter"},
  {name: "Role Playing (RPG)"},
  {name: "Platformer"},
  {name: "Arcade"},
  {name: "Fighting"},
  {name: "Puzzle"},
  {name: "Racing"},
  {name: "Sports"},
  {name: "Strategy/Tactics"},
  {name: "Music"},
  {name: "Action"},
  {name: "E (Everyone)"},
  {name: "T (Teen)"},
  {name: "M (Mature)"}
])

GameTag.create!([
  {game_id: 10, tag_id: 10},
  {game_id: 10, tag_id: 11},
  {game_id: 10, tag_id: 14},
  {game_id: 10, tag_id: 16},
  {game_id: 10, tag_id: 18},
  {game_id: 10, tag_id: 22},
  {game_id: 10, tag_id: 37},
  {game_id: 10, tag_id: 41},
  {game_id: 11, tag_id: 9},
  {game_id: 11, tag_id: 12},
  {game_id: 11, tag_id: 15},
  {game_id: 11, tag_id: 17},
  {game_id: 11, tag_id: 18},
  {game_id: 11, tag_id: 19},
  {game_id: 11, tag_id: 24},
  {game_id: 11, tag_id: 30},
  {game_id: 11, tag_id: 39},
  {game_id: 11, tag_id: 42},
  {game_id: 12, tag_id: 9},
  {game_id: 12, tag_id: 13},
  {game_id: 12, tag_id: 15},
  {game_id: 12, tag_id: 17},
  {game_id: 12, tag_id: 19},
  {game_id: 12, tag_id: 22},
  {game_id: 12, tag_id: 30},
  {game_id: 12, tag_id: 37},
  {game_id: 12, tag_id: 41},
  {game_id: 13, tag_id: 10},
  {game_id: 13, tag_id: 13},
  {game_id: 13, tag_id: 14},
  {game_id: 13, tag_id: 16},
  {game_id: 13, tag_id: 17},
  {game_id: 13, tag_id: 19},
  {game_id: 13, tag_id: 22},
  {game_id: 13, tag_id: 25},
  {game_id: 13, tag_id: 30},
  {game_id: 13, tag_id: 39},
  {game_id: 13, tag_id: 42},
  {game_id: 14, tag_id: 10},
  {game_id: 14, tag_id: 11},
  {game_id: 14, tag_id: 14},
  {game_id: 14, tag_id: 17},
  {game_id: 14, tag_id: 18},
  {game_id: 14, tag_id: 19},
  {game_id: 14, tag_id: 20},
  {game_id: 14, tag_id: 24},
  {game_id: 14, tag_id: 25},
  {game_id: 14, tag_id: 26},
  {game_id: 14, tag_id: 29},
  {game_id: 14, tag_id: 39},
  {game_id: 14, tag_id: 42},
  {game_id: 15, tag_id: 10},
  {game_id: 15, tag_id: 12},
  {game_id: 15, tag_id: 15},
  {game_id: 15, tag_id: 17},
  {game_id: 15, tag_id: 18},
  {game_id: 15, tag_id: 19},
  {game_id: 15, tag_id: 20},
  {game_id: 15, tag_id: 21},
  {game_id: 15, tag_id: 22},
  {game_id: 15, tag_id: 24},
  {game_id: 15, tag_id: 30},
  {game_id: 15, tag_id: 31},
  {game_id: 15, tag_id: 39},
  {game_id: 15, tag_id: 40},
  {game_id: 16, tag_id: 9},
  {game_id: 16, tag_id: 11},
  {game_id: 16, tag_id: 15},
  {game_id: 16, tag_id: 16},
  {game_id: 16, tag_id: 18},
  {game_id: 16, tag_id: 19},
  {game_id: 16, tag_id: 20},
  {game_id: 16, tag_id: 21},
  {game_id: 16, tag_id: 24},
  {game_id: 16, tag_id: 32},
  {game_id: 16, tag_id: 39},
  {game_id: 16, tag_id: 40},
  {game_id: 17, tag_id: 9},
  {game_id: 17, tag_id: 12},
  {game_id: 17, tag_id: 14},
  {game_id: 17, tag_id: 17},
  {game_id: 17, tag_id: 18},
  {game_id: 17, tag_id: 19},
  {game_id: 17, tag_id: 20},
  {game_id: 17, tag_id: 23},
  {game_id: 17, tag_id: 24},
  {game_id: 17, tag_id: 29},
  {game_id: 17, tag_id: 30},
  {game_id: 17, tag_id: 42},
  {game_id: 18, tag_id: 9},
  {game_id: 18, tag_id: 12},
  {game_id: 18, tag_id: 14},
  {game_id: 18, tag_id: 17},
  {game_id: 18, tag_id: 16},
  {game_id: 18, tag_id: 17},
  {game_id: 18, tag_id: 21},
  {game_id: 18, tag_id: 22},
  {game_id: 18, tag_id: 30},
  {game_id: 18, tag_id: 37},
  {game_id: 18, tag_id: 40},
  {game_id: 19, tag_id: 10},
  {game_id: 19, tag_id: 12},
  {game_id: 19, tag_id: 15},
  {game_id: 19, tag_id: 17},
  {game_id: 19, tag_id: 18},
  {game_id: 19, tag_id: 19},
  {game_id: 19, tag_id: 20},
  {game_id: 19, tag_id: 22},
  {game_id: 19, tag_id: 24},
  {game_id: 19, tag_id: 39},
  {game_id: 19, tag_id: 42},
  {game_id: 20, tag_id: 9},
  {game_id: 20, tag_id: 12},
  {game_id: 20, tag_id: 15},
  {game_id: 20, tag_id: 17},
  {game_id: 20, tag_id: 18},
  {game_id: 20, tag_id: 19},
  {game_id: 20, tag_id: 20},
  {game_id: 20, tag_id: 21},
  {game_id: 20, tag_id: 22},
  {game_id: 20, tag_id: 24},
  {game_id: 20, tag_id: 31},
  {game_id: 20, tag_id: 32},
  {game_id: 20, tag_id: 40},
  {game_id: 21, tag_id: 9},
  {game_id: 21, tag_id: 13},
  {game_id: 21, tag_id: 15},
  {game_id: 21, tag_id: 17},
  {game_id: 21, tag_id: 21},
  {game_id: 21, tag_id: 22},
  {game_id: 21, tag_id: 24},
  {game_id: 21, tag_id: 30},
  {game_id: 21, tag_id: 39},
  {game_id: 21, tag_id: 40},
  {game_id: 22, tag_id: 9},
  {game_id: 22, tag_id: 11},
  {game_id: 22, tag_id: 14},
  {game_id: 22, tag_id: 16},
  {game_id: 22, tag_id: 19},
  {game_id: 22, tag_id: 21},
  {game_id: 22, tag_id: 27},
  {game_id: 22, tag_id: 32},
  {game_id: 22, tag_id: 36},
  {game_id: 22, tag_id: 40},
  {game_id: 23, tag_id: 10},
  {game_id: 23, tag_id: 13},
  {game_id: 23, tag_id: 15},
  {game_id: 23, tag_id: 16},
  {game_id: 23, tag_id: 17},
  {game_id: 23, tag_id: 19},
  {game_id: 23, tag_id: 23},
  {game_id: 23, tag_id: 24},
  {game_id: 23, tag_id: 25},
  {game_id: 23, tag_id: 26},
  {game_id: 23, tag_id: 39},
  {game_id: 23, tag_id: 42},
  {game_id: 24, tag_id: 9},
  {game_id: 24, tag_id: 12},
  {game_id: 24, tag_id: 15},
  {game_id: 24, tag_id: 16},
  {game_id: 24, tag_id: 17},
  {game_id: 24, tag_id: 21},
  {game_id: 24, tag_id: 22},
  {game_id: 24, tag_id: 24},
  {game_id: 24, tag_id: 34},
  {game_id: 24, tag_id: 39},
  {game_id: 24, tag_id: 40},
  {game_id: 25, tag_id: 9},
  {game_id: 25, tag_id: 12},
  {game_id: 25, tag_id: 15},
  {game_id: 25, tag_id: 16},
  {game_id: 25, tag_id: 17},
  {game_id: 25, tag_id: 18},
  {game_id: 25, tag_id: 19},
  {game_id: 25, tag_id: 20},
  {game_id: 25, tag_id: 21},
  {game_id: 25, tag_id: 23},
  {game_id: 25, tag_id: 24},
  {game_id: 25, tag_id: 25},
  {game_id: 25, tag_id: 28},
  {game_id: 25, tag_id: 29},
  {game_id: 25, tag_id: 42},
  {game_id: 26, tag_id: 9},
  {game_id: 26, tag_id: 11},
  {game_id: 26, tag_id: 15},
  {game_id: 26, tag_id: 17},
  {game_id: 26, tag_id: 18},
  {game_id: 26, tag_id: 19},
  {game_id: 26, tag_id: 20},
  {game_id: 26, tag_id: 21},
  {game_id: 26, tag_id: 23},
  {game_id: 26, tag_id: 25},
  {game_id: 26, tag_id: 31},
  {game_id: 26, tag_id: 34},
  {game_id: 26, tag_id: 42},
  {game_id: 27, tag_id: 9},
  {game_id: 27, tag_id: 12},
  {game_id: 27, tag_id: 15},
  {game_id: 27, tag_id: 17},
  {game_id: 27, tag_id: 18},
  {game_id: 27, tag_id: 19},
  {game_id: 27, tag_id: 20},
  {game_id: 27, tag_id: 34},
  {game_id: 27, tag_id: 40},
  {game_id: 28, tag_id: 9},
  {game_id: 28, tag_id: 11},
  {game_id: 28, tag_id: 15},
  {game_id: 28, tag_id: 16},
  {game_id: 28, tag_id: 17},
  {game_id: 28, tag_id: 17},
  {game_id: 28, tag_id: 18},
  {game_id: 28, tag_id: 19},
  {game_id: 28, tag_id: 22},
  {game_id: 28, tag_id: 24},
  {game_id: 28, tag_id: 31},
  {game_id: 28, tag_id: 40},
  {game_id: 29, tag_id: 9},
  {game_id: 29, tag_id: 12},
  {game_id: 29, tag_id: 15},
  {game_id: 29, tag_id: 17},
  {game_id: 29, tag_id: 19},
  {game_id: 29, tag_id: 24},
  {game_id: 29, tag_id: 39},
  {game_id: 29, tag_id: 41},
  {game_id: 30, tag_id: 10},
  {game_id: 30, tag_id: 12},
  {game_id: 30, tag_id: 15},
  {game_id: 30, tag_id: 17},
  {game_id: 30, tag_id: 19},
  {game_id: 30, tag_id: 22},
  {game_id: 30, tag_id: 24},
  {game_id: 30, tag_id: 30},
  {game_id: 30, tag_id: 39},
  {game_id: 30, tag_id: 42},
  {game_id: 31, tag_id: 10},
  {game_id: 31, tag_id: 12},
  {game_id: 31, tag_id: 14},
  {game_id: 31, tag_id: 17},
  {game_id: 31, tag_id: 18},
  {game_id: 31, tag_id: 19},
  {game_id: 31, tag_id: 20},
  {game_id: 31, tag_id: 23},
  {game_id: 31, tag_id: 24},
  {game_id: 31, tag_id: 30},
  {game_id: 31, tag_id: 39},
  {game_id: 31, tag_id: 42}
])

User.create!([
  {name: "Justin", email: "j@gmail.com", password_digest: "$2a$12$KjKVDmNka1JYjBomXEwVnesuSN7PKuFVgrSVNWcn73p2WRwg3oErm"}
])
